# Generated by Django 5.0.3 on 2024-04-23 15:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatarmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useravatarmodel',
            name='avatar',
            field=models.ImageField(upload_to=account.models.avatar_path),
        ),
    ]
