# Generated by Django 5.0.3 on 2024-03-18 10:23

import account.utils.avatar_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatarmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useravatarmodel',
            name='avatar',
            field=models.ImageField(upload_to=account.utils.avatar_path.avatar_path),
        ),
    ]
